version: '3.8'

services:
  backend:
    container_name: cod-mon-api
    image: 'ghcr.io/lnls-sirius/cod-mon-backend:1.0.0'
    build:
      context: ./back_end
    ports:
      - 80:80
  frontend:
    container_name: cod-mon
    image: 'ghcr.io/lnls-sirius/cod-mon-frontend:1.0.0'
    build:
      context: ./front_end
    ports:
      - 80:80
