name: COD Monitor CD

on:
  pull_request:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@master
      - name: p1
        run: pwd
      - name: t2
        run: ls
      - name: t5
        run: cd ./front_end
      - name: t6
        run: ls
      - name: t3
        run: cd ../../
      - name: t4
        run: ls
      - name: Run Docker Compose ğŸ³
        run: docker-compose build
